name: picauth
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  injectable: ^2.1.1
  get_it: ^7.2.0
  provider: ^6.0.5
  cryptography_flutter: ^2.3.0
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  lottie: ^2.3.2

flutter_gen:
  integrations:
    lottie: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
